repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort ./app
        language: python
        types: [ python ]

      - id: black
        name: black
        entry: black ./app
        language: python
        types: [ python ]

      - id: flake8
        name: flake8
        entry: pflake8 --format=html --htmldir=./flake-report ./app
        language: python
        types: [ python ]

      - id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [ python ]
        pass_filenames: false
        always_run: true
